#include "pwm.h"                /* INCLUDE HEADER FOR PWM FUNCTIONS */
#include "stm32f091xc.h"        /* INCLUDE STM32F091 MICROCONTROLLER DEFINITIONS */
#include "stm32f0xx.h"          /* INCLUDE STM32F0 SPECIFIC HEADER */
#include "system_config.h"      /* INCLUDE HEADER FOR SYSTEM CONFIGURATION */

/* FUNCTION TO INITIALIZE PWM USING TIMER2 */
void PWM_Init(void){


    RCC->AHBENR |= RCC_AHBENR_GPIOAEN;         /* ENABLE GPIOA CLOCK */
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN;        /* ENABLE TIMER2 CLOCK */

    GPIOA->MODER &= ~(3U << (5 * 2));          /* CLEAR MODE BITS FOR PA5 */
    GPIOA->MODER |= (2U << (5 * 2));           /* SET PA5 TO ALTERNATE FUNCTION MODE */
    GPIOA->AFR[0] &= ~(0xFU << (5 * 4));       /* CLEAR ALTERNATE FUNCTION BITS FOR PA5 */
    GPIOA->AFR[0] |= (2U << (5 * 4));/* SET ALTERNATE FUNCTION 2 FOR PA5 (TIM2) */

    TIM2->PSC = 20; /* SET PRESCALER TO 20 */
    TIM2->ARR = 999;  /* SET AUTO-RELOAD VALUE TO 999 (PERIOD) */

    TIM2->CCMR1 &= ~TIM_CCMR1_OC1M;/* CLEAR OUTPUT COMPARE MODE BITS */
    TIM2->CCMR1 |= (6U << 4);/* SET OUTPUT COMPARE MODE TO PWM MODE 1 */
    TIM2->CCMR1 |= TIM_CCMR1_OC1PE;/* ENABLE OUTPUT COMPARE PRELOAD */

    TIM2->CCER |= TIM_CCER_CC1E;/* ENABLE OUTPUT COMPARE CHANNEL 1 */

    TIM2->CR1 |= TIM_CR1_CEN; /* ENABLE TIMER2 COUNTER */
    TIM2->CCR1 = 900;/* SET INITIAL DUTY CYCLE TO 90% */
}



/* FUNCTION TO SET TONE STATE */
void PWM_SetTone(uint32_t state){

    if (state == 0){

        TIM2->CCR1 = 0; /* TURN OFF SOUND BY SETTING DUTY CYCLE TO 0% */
    } else
    {
        TIM2->CCR1 = 1; /* TURN ON SOUND BY SETTING MINIMAL DUTY CYCLE */
    }
}

/* FUNCTION TO PLAY ALERT TONE */
void PlayAlertTone(void)
{
    TIM2->CCR1 = 1; /* TURN ON SQUARE WAVE OUTPUT */
    Delay(200000);/* WAIT FOR A SHORT DURATION */
    TIM2->CCR1 = 0;/* TURN OFF SQUARE WAVE OUTPUT */
}
